update deploy.yml
secret 변수 확인

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,12 +19,26 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+      - name: Check if secrets are set
+        run: |
+          if [[ -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
+            echo "❌ ERROR: DOCKER_USERNAME is not set!"
+            exit 1
+          fi
+
+          if [[ -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
+            echo "❌ ERROR: DOCKER_PASSWORD is not set!"
+            exit 1
+          fi
+
+          echo "✅ All required secrets are set!"
 
       - name: Login to Docker Hub
         run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
       - name: Docker build & push to DockerHub
         run: |
